import { useState } from 'react'
import type { AnalysisReport } from '../data/types'
import { loadSettings, saveSettings } from '../storage/settings'

function reportToPlainText(report: AnalysisReport): string {
  const lines = [
    `SYNCMFG report: ${report.title}`,
    '',
    report.summary,
    '',
    ...report.bullets.map((b) => `• ${b}`),
    '',
    '— Generated by SYNCMFG',
  ]
  return lines.join('\n')
}

function reportToHtml(report: AnalysisReport): string {
  const bullets = report.bullets.map((b) => `<li>${escapeHtml(b)}</li>`).join('')
  return `<!doctype html>
<html><head><meta charset="utf-8"/><title>${escapeHtml(report.title)}</title>
<style>
  body{font-family:Georgia,serif;max-width:720px;margin:2rem auto;padding:0 1rem;color:#152028;line-height:1.5}
  h1{font-family:Arial,sans-serif;color:#1a3a3a}
  .brand{letter-spacing:.08em;text-transform:uppercase;color:#2f6f6a;font-weight:700;font-size:.85rem}
</style></head>
<body>
  <p class="brand">SYNCMFG</p>
  <h1>${escapeHtml(report.title)}</h1>
  <p>${escapeHtml(report.summary)}</p>
  <ul>${bullets}</ul>
  <p><small>Generated by SYNCMFG · data auto-expires after 30 days in the app</small></p>
</body></html>`
}

function escapeHtml(s: string): string {
  return s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
}

export function ShareReport({ report }: { report: AnalysisReport }) {
  const initial = loadSettings()
  const [email, setEmail] = useState(initial.lastEmail)
  const [note, setNote] = useState('')
  const [busy, setBusy] = useState(false)
  const hasServer = Boolean(initial.web3formsKey)

  function rememberEmail(value: string) {
    setEmail(value)
    saveSettings({ ...loadSettings(), lastEmail: value })
  }

  function handleMailto() {
    const to = email.trim()
    if (!to || !to.includes('@')) {
      setNote('Enter a full email address (example: name@company.com).')
      return
    }
    const body = reportToPlainText(report)
    const subject = `SYNCMFG: ${report.title}`
    window.location.href = `mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
    setNote(
      'Opened your email app with the report filled in. If the body looks cut off, use Download HTML or Print/PDF.',
    )
  }

  async function handleServerSend() {
    const to = email.trim()
    const key = loadSettings().web3formsKey
    if (!key) {
      setNote('Add a Web3Forms key under Settings first.')
      return
    }
    if (!to || !to.includes('@')) {
      setNote('Enter a full email address.')
      return
    }
    setBusy(true)
    setNote('')
    try {
      const res = await fetch('https://api.web3forms.com/submit', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          access_key: key,
          subject: `SYNCMFG: ${report.title}`,
          from_name: 'SYNCMFG',
          email: to,
          message: reportToPlainText(report),
        }),
      })
      const data = (await res.json()) as { success?: boolean; message?: string }
      if (!res.ok || !data.success) {
        throw new Error(data.message || 'Send failed')
      }
      setNote(`Sent from SYNCMFG to ${to}.`)
    } catch (err) {
      setNote(
        err instanceof Error
          ? err.message
          : 'Could not send. Check your Web3Forms key or use Email / Download.',
      )
    } finally {
      setBusy(false)
    }
  }

  function handleDownload() {
    const blob = new Blob([reportToHtml(report)], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `syncmfg-${report.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.html`
    a.click()
    URL.revokeObjectURL(url)
    setNote('Downloaded an HTML report you can attach to any email.')
  }

  function handlePrint() {
    const html = reportToHtml(report)
    const w = window.open('', '_blank', 'noopener,noreferrer')
    if (!w) {
      setNote('Pop-up blocked — allow pop-ups or use Download HTML.')
      return
    }
    w.document.write(html)
    w.document.close()
    w.focus()
    w.print()
    setNote('Print dialog opened — choose Save as PDF or a printer.')
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(reportToPlainText(report))
      setNote('Report copied. Paste it into email, Teams, or Notes.')
    } catch {
      setNote('Could not copy automatically — use Download HTML instead.')
    }
  }

  return (
    <section className="share-report panel soft no-print">
      <h3>Send or save this report</h3>
      <p className="lede">
        Works from any factory Wi‑Fi. Print/PDF is great for handing a supervisor
        a clean page.
      </p>
      <label htmlFor="report-email">Email to</label>
      <input
        id="report-email"
        type="email"
        placeholder="name@company.com"
        value={email}
        onChange={(e) => {
          rememberEmail(e.target.value)
          setNote('')
        }}
      />
      <div className="row actions">
        <button type="button" className="btn primary" onClick={handleMailto}>
          Email (mail app)
        </button>
        {hasServer ? (
          <button
            type="button"
            className="btn primary"
            disabled={busy}
            onClick={handleServerSend}
          >
            {busy ? 'Sending…' : 'Send from SYNCMFG'}
          </button>
        ) : null}
        <button type="button" className="btn secondary" onClick={handlePrint}>
          Print / PDF
        </button>
        <button type="button" className="btn secondary" onClick={handleDownload}>
          Download HTML
        </button>
        <button type="button" className="btn secondary" onClick={handleCopy}>
          Copy text
        </button>
      </div>
      {note ? <p className="share-note">{note}</p> : null}
    </section>
  )
}
